import { StyleSheet } from "react-native";
import { C } from "../theme/theme";

export const styles=StyleSheet.create({
header:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",marginBottom:20},eyebrow:{color:C.muted,fontSize:12,textAlign:"right"},greeting:{color:C.text,fontSize:25,fontWeight:"800",textAlign:"right",marginTop:4},bell:{width:44,height:44,borderRadius:15,backgroundColor:C.panel,borderWidth:1,borderColor:C.border,alignItems:"center",justifyContent:"center",position:"relative"},bellText:{color:C.text,fontSize:25},dot:{position:"absolute",top:9,right:10,width:7,height:7,borderRadius:4,backgroundColor:C.cyan},
days:{flexDirection:"row",gap:9,paddingBottom:18},day:{width:48,height:64,borderRadius:16,backgroundColor:C.panel,borderWidth:1,borderColor:C.border,alignItems:"center",justifyContent:"center"},dayActive:{backgroundColor:C.cyan,borderColor:C.cyan},dayLabel:{color:C.muted,fontSize:12,fontWeight:"700",marginBottom:5},dayDate:{color:C.text,fontSize:17,fontWeight:"800"},activeText:{color:C.bg},
section:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",marginBottom:12},sectionTitle:{color:C.text,fontSize:16,fontWeight:"800",textAlign:"right"},action:{color:C.cyan,fontSize:11,fontWeight:"700"},
meta:{color:C.muted,fontSize:11,textAlign:"right",marginTop:4},classTitle:{color:C.text,fontSize:14,fontWeight:"800",textAlign:"right"},time:{width:55,color:C.muted,fontSize:11,fontWeight:"700",textAlign:"right"},
next:{backgroundColor:C.panel2,borderRadius:24,padding:20,borderWidth:1,borderColor:"#293044",marginBottom:24},nextHead:{flexDirection:"row-reverse",justifyContent:"space-between"},cyanText:{color:C.cyan,fontSize:12,fontWeight:"700",textAlign:"right",marginBottom:7},nextTitle:{color:C.text,fontSize:22,fontWeight:"800",textAlign:"right",marginBottom:6},bigIcon:{width:48,height:48,borderRadius:16,backgroundColor:"#63E6FF15",borderWidth:1,borderColor:"#63E6FF35",alignItems:"center",justifyContent:"center"},bigIconText:{color:C.cyan,fontSize:25,fontWeight:"800"},nextBottom:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"flex-end",marginTop:22},bigTime:{color:C.text,fontSize:25,fontWeight:"900",textAlign:"right"},count:{color:C.cyan,fontSize:30,fontWeight:"900"},
timeline:{marginBottom:22},trow:{flexDirection:"row-reverse",minHeight:72},lineCol:{width:22,alignItems:"center"},tdot:{width:10,height:10,borderRadius:5,marginTop:4},line:{width:1,flex:1,backgroundColor:C.border,marginTop:4},classItem:{flex:1,flexDirection:"row-reverse",gap:10,paddingBottom:13},mini:{width:36,height:36,borderRadius:12,backgroundColor:C.panel,borderWidth:1,alignItems:"center",justifyContent:"center"},miniText:{fontSize:16,fontWeight:"900"},
row:{flexDirection:"row",gap:10,paddingBottom:22},task:{width:185,minHeight:118,borderRadius:19,padding:15,backgroundColor:C.panel,borderWidth:1,borderColor:C.border},done:{opacity:.58},taskTop:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",marginBottom:12},badge:{paddingHorizontal:8,paddingVertical:4,borderRadius:8,fontSize:9,fontWeight:"800"},check:{color:C.muted,fontSize:19},taskTitle:{color:C.text,fontSize:12,lineHeight:19,fontWeight:"700",textAlign:"right"},strike:{textDecorationLine:"line-through"},
card:{backgroundColor:C.panel,borderRadius:20,borderWidth:1,borderColor:C.border,padding:16,marginBottom:16},goalHead:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},percent:{color:C.green,fontSize:20,fontWeight:"900"},track:{height:7,backgroundColor:C.border,borderRadius:4,overflow:"hidden",marginTop:14,marginBottom:8},fill:{height:"100%",width:"78%",backgroundColor:C.green},motivation:{padding:20,borderRadius:20,backgroundColor:"#9B7CFF12",borderWidth:1,borderColor:"#9B7CFF25"},quote:{color:C.purple,fontSize:35,textAlign:"right"},motText:{color:C.text,fontSize:15,fontWeight:"800",textAlign:"right",lineHeight:24},
pageTitle:{alignItems:"flex-end",marginBottom:22},pageTitleText:{color:C.text,fontSize:26,fontWeight:"900",textAlign:"right",marginBottom:5},scheduleRow:{flexDirection:"row-reverse",alignItems:"center",minHeight:72,borderBottomWidth:1,borderBottomColor:C.border},scheduleBar:{width:3,height:42,borderRadius:2,marginHorizontal:12},fullTask:{flexDirection:"row-reverse",alignItems:"center",gap:12,paddingVertical:14,borderBottomWidth:1,borderBottomColor:C.border},fullCheck:{width:26,height:26,borderRadius:9,borderWidth:1,borderColor:C.border,alignItems:"center",justifyContent:"center"},fullCheckDone:{backgroundColor:C.green,borderColor:C.green},add:{backgroundColor:C.cyan,borderRadius:16,padding:16,alignItems:"center"},addText:{color:C.bg,fontSize:13,fontWeight:"900"},
stats:{flexDirection:"row-reverse",flexWrap:"wrap",gap:10,marginBottom:16},stat:{width:"48%",backgroundColor:C.panel,borderWidth:1,borderColor:C.border,borderRadius:18,padding:15,minHeight:110},statValue:{color:C.text,fontSize:25,fontWeight:"900",textAlign:"right",marginVertical:10},bars:{height:150,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-around",marginTop:20},barItem:{alignItems:"center",justifyContent:"flex-end",height:"100%"},bar:{width:20,borderRadius:8,backgroundColor:C.cyan,opacity:.8},
nav:{position:"absolute",left:12,right:12,bottom:12,height:72,borderRadius:24,backgroundColor:"#11141DED",borderWidth:1,borderColor:C.border,flexDirection:"row-reverse",justifyContent:"space-around",alignItems:"center"},navItem:{alignItems:"center",width:"25%"},navIcon:{width:35,height:32,alignItems:"center",justifyContent:"center",borderRadius:11},navIconActive:{backgroundColor:"#63E6FF18"},navIconText:{color:C.muted,fontSize:18,fontWeight:"800"},navLabel:{color:C.muted,fontSize:9,marginTop:3,fontWeight:"700"},cyan:{color:C.cyan}
});
